import requests
import json
import logging
from django.conf import settings
from django.urls import reverse
from django.db.models import Count
from django_otp.plugins.otp_totp.models import TOTPDevice

logger = logging.getLogger(__name__)

class BaseAIProvider:
    """Base interface for all AI provider engines (Gemini, OpenAI, Local, etc.)"""
    def generate_response(self, system_instruction, user_prompt, context):
        raise NotImplementedError("Providers must implement generate_response")

class GeminiProvider(BaseAIProvider):
    """Google Gemini API Provider implementation using raw HTTP requests"""
    
    def generate_response(self, system_instruction, user_prompt, context):
        api_key = getattr(settings, 'GEMINI_API_KEY', None)
        if not api_key:
            raise ValueError("Gemini API key is not configured.")
        
        # Standard endpoint for Gemini 1.5 Flash
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}"
        
        headers = {
            'Content-Type': 'application/json'
        }
        
        # Combine system instruction, context summary, and user question
        full_prompt = f"{system_instruction}\n\n[USER CONTEXT]\n{json.dumps(context, indent=2)}\n\nUser Question: {user_prompt}"
        
        payload = {
            "contents": [{
                "parts": [{"text": full_prompt}]
            }]
        }
        
        try:
            response = requests.post(url, headers=headers, json=payload, timeout=8)
            if response.status_code == 200:
                res_data = response.json()
                # Parse response text
                text = res_data['candidates'][0]['content']['parts'][0]['text']
                return text, False # (response text, is_fallback)
            else:
                logger.error(f"Gemini API returned status code {response.status_code}: {response.text}")
                raise Exception("Gemini API call failed")
        except Exception as e:
            logger.error(f"Error calling Gemini API: {str(e)}")
            raise e

class FallbackProvider(BaseAIProvider):
    """Local, intelligent, rule-based Fallback Security Advisor"""
    
    def generate_response(self, system_instruction, user_prompt, context):
        prompt_lower = user_prompt.lower()
        score = context.get('security_score', 100)
        has_2fa = context.get('has_active_2fa', False)
        total_checks = context.get('total_checks', 0)
        compromised = context.get('compromised_count', 0)
        reused = context.get('reused_count', 0)
        
        response_lines = [
            "**AI Security Assistant Advisor** (Offline Security Mode)\n",
            "Here is my analysis based on your security profile:\n"
        ]
        
        # 1. Score and Improvements
        if any(x in prompt_lower for x in ["score", "improvement", "improve", "increase"]):
            response_lines.append(f"* Your current overall security score is **{score}%**.")
            if not has_2fa:
                response_lines.append("* **2FA is Disabled**: This is a major vulnerability. Enabling Two-Factor Authentication will recover +20 points.")
            if total_checks == 0:
                response_lines.append("* **No Audits**: You haven't run any audits yet. Run a check on the homepage to remove the first-audit penalty (+20 points).")
            if compromised > 0:
                response_lines.append(f"* **Compromised Credentials**: We found **{compromised}** breached password records in your history, deducting **{compromised * 15} points**.")
            if reused > 0:
                response_lines.append(f"* **Reused Passwords**: You have **{reused}** duplicate password checks, deducting **{reused * 10} points**.")
            if score >= 80:
                response_lines.append("\nGreat job! Your profile meets recommended security standards. Keep utilizing unique passwords.")
            else:
                response_lines.append("\n**Recommendation**: Go to **Settings -> Security** to enable 2FA, and replace any compromised or duplicate credentials shown in your History tab.")
        
        # 2. 2FA / MFA
        elif any(x in prompt_lower for x in ["2fa", "two-factor", "mfa", "multi-factor", "factor"]):
            response_lines.append(
                "**Two-Factor Authentication (2FA)** adds a second layer of security to your account:\n"
                "1. **Something You Know**: Your password.\n"
                "2. **Something You Have**: A dynamic 6-digit verification code generated by an app on your phone (Google Authenticator, Authy).\n\n"
                "Even if a hacker manages to compromise your password, they cannot gain access to your account without your physical phone. You should enable 2FA on every service that supports it."
            )
            
        # 3. k-Anonymity & SHA-1 / Hashing / Encryption
        elif any(x in prompt_lower for x in ["k-anonymity", "anonymity", "sha", "hash", "encrypt"]):
            response_lines.append(
                "**k-Anonymity and Hashing** are cryptographic models used to check passwords securely:\n"
                "1. **SHA-1 Hashing**: Your password is locally converted to a SHA-1 hash (e.g. `5BAA61E4C9B93F3...`). This is a one-way mathematical function.\n"
                "2. **The 5-Character Prefix**: We send only the first 5 characters (`5BAA6`) to the HaveIBeenPwned API. This is called a range query.\n"
                "3. **Local Comparison**: The server returns a list of matching hashes, and your browser checks if the full hash matches locally.\n\n"
                "**Security Guarantee**: Your actual password or full hash never leaves your device, keeping your credentials fully anonymous."
            )
            
        # 4. Entropy
        elif "entropy" in prompt_lower:
            response_lines.append(
                "**Password Entropy** measures the complexity and randomness of a password in bits:\n"
                "* **High Entropy** (e.g. >80 bits) indicates a password that is practically un-crackable by modern computers.\n"
                "* **Low Entropy** (e.g. <45 bits) suggests common sequences, short lengths, or words from a dictionary.\n\n"
                "Entropy is calculated based on the formula: **Entropy = Length * Log2(Charset Size)**. Thus, increasing password length is the most effective way to boost entropy."
            )
            
        # 5. Weak / Strong / Strength
        elif any(x in prompt_lower for x in ["weak", "strong", "strength"]):
            response_lines.append(
                "Password strength is determined by four key indicators:\n"
                "1. **Length**: At least 12-16 characters is recommended.\n"
                "2. **Complexity**: Mix of uppercase, lowercase, numbers, and special symbols.\n"
                "3. **Uniqueness**: Never reuse passwords across accounts.\n"
                "4. **Leaked Status**: A password that has appeared in data breaches is insecure, no matter how complex it is.\n\n"
                "Ensure you audit your passwords on our homepage and use the built-in Secure Generator."
            )
            
        # 6. Cracking / Hackers / Brute Force / Dictionary / Credential Stuffing
        elif any(x in prompt_lower for x in ["crack", "hack", "brute", "dictionary", "stuffing", "attack"]):
            response_lines.append(
                "Hackers compromise credentials using three main automated methods:\n"
                "1. **Brute Force**: Trying all possible combinations of characters (fast against short passwords).\n"
                "2. **Dictionary Attacks**: Testing lists of popular words and patterns (e.g., `Spring2026!`).\n"
                "3. **Credential Stuffing**: Using leaked credentials from one site to automate logins on other platforms.\n\n"
                "Using unique passwords for every service and enabling 2FA blocks 100% of automated credential stuffing attacks."
            )
            
        # 7. Data Breaches / Leak / Compromised
        elif any(x in prompt_lower for x in ["breach", "leak", "compromised", "pwned"]):
            response_lines.append(
                "A **Data Breach** occurs when an external server is compromised, exposing their database of user emails and passwords.\n"
                "Once leaked, these credentials are added to public collections and used by automated scripts to gain unauthorized access.\n\n"
                "If a password of yours has been found in a data breach, you must **change it immediately** on all accounts where you have used it."
            )
            
        # 8. Password Managers
        elif "manager" in prompt_lower:
            response_lines.append(
                "A **Password Manager** (like Bitwarden, 1Password, or KeePass) is a secure, encrypted vault for storing your credentials.\n"
                "It allows you to use highly complex, unique passwords for every website without needing to remember them. You only need to remember one master password."
            )
            
        # 9. Social Engineering / Phishing
        elif any(x in prompt_lower for x in ["phish", "social", "scam"]):
            response_lines.append(
                "**Social Engineering & Phishing** are attacks that target the human element rather than technical systems:\n"
                "* **Phishing**: Fake emails or websites pretending to be legitimate brands prompting you to type your password.\n"
                "* **Social Engineering**: Manipulating you to reveal security codes or reset questions.\n\n"
                "Always verify the website URL before logging in, and never share verification codes with anyone."
            )
            
        # 10. Zero Trust
        elif "zero" in prompt_lower or "trust" in prompt_lower:
            response_lines.append(
                "**Zero Trust** is a cybersecurity model based on the principle of: **Never Trust, Always Verify**.\n"
                "It assumes threats exist inside and outside the network. Every user and device must be authenticated and authorized continuously before receiving access to apps and data."
            )
            
        # 11. Hashing & Hashing algorithms
        elif "hashing" in prompt_lower or "hash" in prompt_lower:
            response_lines.append(
                "**Hashing** is a one-way mathematical function that maps data of arbitrary size to a fixed-size bit string:\n"
                "* It is **non-reversible** (you cannot retrieve the password from its hash).\n"
                "* It is **deterministic** (the same password always generates the same hash).\n"
                "This platform uses SHA-1 hashes to securely verify password breaches via HaveIBeenPwned."
            )
            
        # 12. General fallback
        else:
            response_lines.append(
                "I can analyze your security settings and answer questions about:\n"
                "* **Security Score**: *'Explain my security score'*\n"
                "* **2FA / MFA**: *'Should I enable 2FA?'*\n"
                "* **k-Anonymity & Hashing**: *'What is k-Anonymity?'*\n"
                "* **Entropy & Complexity**: *'What is password entropy?'*\n"
                "* **Hackers / Cracking**: *'How do hackers crack passwords?'*\n"
                "* **Data Breaches**: *'Explain data breaches'*"
            )
            
        return "\n".join(response_lines), True

class ContextBuilder:
    """Assembles localized user statistics, audit logs, and status records"""
    
    @staticmethod
    def build_user_context(user):
        if not user or user.is_anonymous:
            return {
                "user_authenticated": False,
                "security_score": 0,
                "total_checks": 0,
                "has_active_2fa": False,
                "compromised_count": 0,
                "reused_count": 0,
                "recent_checks": []
            }
            
        # Get checks
        from password_checker.models import PasswordCheck
        checks = PasswordCheck.objects.filter(user=user)
        total_checks = checks.count()
        compromised = checks.filter(was_breached=True).count()
        
        # Reuse calculation
        reused_groups = checks.values('sha256_hash').annotate(count=Count('id')).filter(count__gt=1)
        reused_count = sum(group['count'] for group in reused_groups) if reused_groups else 0
        
        # Check 2FA
        has_2fa = user.use_two_factor or user.has_active_2fa
        
        # Calculate score dynamically
        score = 100
        if not has_2fa:
            score -= 20
        if total_checks == 0:
            score -= 20
        else:
            if compromised > 0:
                score -= (compromised * 15)
            if reused_count > 0:
                score -= (reused_count * 10)
        score = max(0, min(100, score))
        
        # Recent checks
        recent_list = []
        for c in checks[:5]:
            recent_list.append({
                "hash_prefix": c.hash_prefix,
                "was_breached": c.was_breached,
                "breach_count": c.breach_count,
                "strength_score": float(c.strength_score) if c.strength_score else 0.0,
                "check_timestamp": c.check_timestamp.strftime("%Y-%m-%d %H:%M")
            })
            
        return {
            "user_authenticated": True,
            "username": user.username,
            "security_score": score,
            "total_checks": total_checks,
            "has_active_2fa": has_2fa,
            "compromised_count": compromised,
            "reused_count": reused_count,
            "recent_checks": recent_list
        }

class PromptBuilder:
    """Builds system instructions and prompt context"""
    
    @staticmethod
    def get_system_instruction():
        return (
            "You are 'Sentinel AI', a friendly, highly professional cybersecurity assistant integrated "
            "into the Password Security Platform. Your job is to answer the user's questions about security, "
            "password auditing, and data breaches.\n\n"
            "CRITICAL SECURITY GUIDELINES:\n"
            "1. NEVER ask for, show, or discuss plain-text passwords.\n"
            "2. NEVER reveal sensitive backend server keys or file paths.\n"
            "3. Refer directly to the user's personal context data provided below to give personalized advice.\n"
            "4. Format your responses clearly using Markdown headings, bullet points, and bold text."
        )

class AIService:
    """AI Service router selecting providers dynamically with seamless fallback"""
    
    @staticmethod
    def chat(user, user_prompt):
        context = ContextBuilder.build_user_context(user)
        system_instruction = PromptBuilder.get_system_instruction()
        
        api_key = getattr(settings, 'GEMINI_API_KEY', None)
        
        # If API key exists, try Gemini Provider
        if api_key:
            try:
                provider = GeminiProvider()
                return provider.generate_response(system_instruction, user_prompt, context)
            except Exception as e:
                logger.warning(f"GeminiProvider failed, falling back to local advisor: {str(e)}")
        
        # Fall back to local rule-based expert advisor
        provider = FallbackProvider()
        return provider.generate_response(system_instruction, user_prompt, context)
