# Generated by Django 5.2 on 2026-07-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_prefix', models.CharField(max_length=5)),
                ('sha256_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('check_timestamp', models.DateTimeField(auto_now_add=True)),
                ('was_breached', models.BooleanField(default=False)),
                ('breach_count', models.IntegerField(default=0)),
                ('breach_details', models.JSONField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('strength_score', models.FloatField(default=0.0)),
                ('entropy', models.FloatField(default=0.0)),
                ('crack_time', models.CharField(blank=True, max_length=100)),
                ('recommendation', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Password Checks',
                'ordering': ['-check_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PasswordStrengthAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_prefix', models.CharField(max_length=5)),
                ('strength_score', models.FloatField()),
                ('entropy', models.FloatField(default=0.0)),
                ('crack_time', models.CharField(blank=True, max_length=100)),
                ('analysis_timestamp', models.DateTimeField(auto_now_add=True)),
                ('recommendations', models.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Password Strength Analyses',
                'ordering': ['-analysis_timestamp'],
            },
        ),
    ]
