# Generated by Django 5.2 on 2026-07-01 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('password_checker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordcheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordstrengthanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strength_analyses', to=settings.AUTH_USER_MODEL),
        ),
    ]
